const projectsInfo = [
  {
    id: 1,
    stack: 'React, Redux Toolkit, SCSS, TS',
    title: 'Pizza Delivery',
    description: 'Food delivery site with full functionality.',
    repository: 'https://github.com/FreightDH/pizza-delivery',
    deploy: 'https://freightdh.github.io/pizza-delivery/',
  },
  {
    id: 2,
    stack: 'React, SCSS, TS',
    title: 'Posts App',
    description:
      'Posts App with authorization system, pagination and the ability to view, delete and edit posts.',
    repository: 'https://github.com/FreightDH/react-projects',
    deploy: 'https://freightdh-posts-app.netlify.app/',
  },
  {
    id: 3,
    stack: 'React, Redux Toolkit, SCSS, TS',
    title: 'TODO App',
    description: 'Simple task manager with the ability to add, delete, edit and save your tasks.',
    repository: 'https://github.com/FreightDH/react-projects',
    deploy: 'https://freightdh.github.io/react-projects/todo-app/',
  },
  {
    id: 4,
    stack: 'React, SCSS, TS',
    title: 'Pokemon Cards',
    description: 'Pokemon API with navigation using React Router, custom pagination and popup pokemon card.',
    repository: 'https://github.com/FreightDH/rss-react/tree/main',
    deploy: 'https://freightdh-react-routing.netlify.app',
  },
  {
    id: 5,
    stack: 'HTML, SCSS, JS',
    title: 'Golden Ring',
    description: 'Website guide to one of the most popular tourist routes "Golden Ring".',
    repository: 'https://github.com/FreightDH/golden-ring',
    deploy: 'https://freightdh.github.io/golden-ring/',
  },
  {
    id: 6,
    stack: 'HTML, SCSS, JS',
    title: 'Minesweeper',
    description: 'Minesweeper game with original design.',
    repository: 'https://github.com/FreightDH/minesweeper',
    deploy: 'https://freightdh-minesweeper.netlify.app',
  },
  {
    id: 7,
    stack: 'HTML, SCSS, JS',
    title: 'Virtual keyboard',
    description: 'A virtual keyboard that supports keyboard or mouse input, two languages.',
    repository: 'https://github.com/FreightDH/virtual-keyboard',
    deploy: 'https://freightdh.github.io/virtual-keyboard/virtual-keyboard/',
  },
  {
    id: 8,
    stack: 'HTML, SCSS, JS',
    title: 'Hangman Game',
    description: 'Guessing game with JavaScript questions and responsive design.',
    repository: 'https://github.com/FreightDH/hangman',
    deploy: 'https://freightdh.github.io/hangman/',
  },
  {
    id: 9,
    stack: 'HTML, SCSS, JS',
    title: 'Shelter',
    description: 'Website of the shelter for dogs.',
    repository: 'https://github.com/FreightDH/shelter',
    deploy: 'https://freightdh.github.io/shelter/shelter/',
  },
  {
    id: 10,
    stack: 'HTML, SCSS, JS',
    title: 'Plants',
    description: 'Website with garden care services.',
    repository: 'https://github.com/FreightDH/plants',
    deploy: 'https://freightdh.github.io/plants/plants/',
  },
  {
    id: 11,
    stack: 'HTML, SCSS, JS',
    title: 'Momentum',
    description: 'An analogue of the application with the same name from the Chrome extensions store.',
    repository: 'https://github.com/FreightDH/momentum',
    deploy: 'https://freightdh-momentum.netlify.app/',
  },
];

export default projectsInfo;
