const projectsInfo = {
  eng: [
    {
      id: 3,
      stack: 'HTML, CSS, JS, PHP',
      title: 'ООО «ЛМК-ИНЖИНИРИНГ»',
      description: 'Reliable solution for oil and gas grade pipes',
      repository: '',
      deploy: 'https://lmk-engineering.ru/',
    },
    {
      id: 2,
      stack: 'React, SCSS, JS',
      title: 'Shift_',
      description: 'Shift_ - fast and confident entry into IT here.',
      repository: 'https://github.com/FreightDH/shift_',
      deploy: 'https://freightdh-shift.netlify.app/',
    },
    {
      id: 12,
      stack: 'HTML, SCSS, JS',
      title: '7 Months Club',
      description:
        'The 7 Months Club is a single product delivery service - a desired offerer to an IT company - in 7 months or less.',
      repository: 'https://github.com/FreightDH/7-months-club',
      deploy: 'https://freightdh.github.io/7-months-club/',
    },
    {
      id: 11,
      stack: 'React, Redux Toolkit, SCSS, TS',
      title: 'Pizza Delivery',
      description: 'Food delivery site with full functionality.',
      repository: 'https://github.com/FreightDH/pizza-delivery',
      deploy: 'https://freightdh.github.io/pizza-delivery/',
    },
    {
      id: 10,
      stack: 'React, SCSS, TS',
      title: 'Posts App',
      description:
        'Posts App with authorization system, pagination and the ability to view, delete and edit posts.',
      repository: 'https://github.com/FreightDH/react-projects',
      deploy: 'https://freightdh-posts-app.netlify.app/',
    },
    {
      id: 9,
      stack: 'React, Redux Toolkit, SCSS, TS',
      title: 'TODO App',
      description: 'Simple task manager with the ability to add, delete, edit and save your tasks.',
      repository: 'https://github.com/FreightDH/react-projects',
      deploy: 'https://freightdh.github.io/react-projects/todo-app/',
    },
    {
      id: 8,
      stack: 'React, SCSS, TS',
      title: 'Pokemon Cards',
      description:
        'Pokemon API with navigation using React Router, custom pagination and popup pokemon card.',
      repository: 'https://github.com/FreightDH/rss-react/tree/main',
      deploy: 'https://freightdh-react-routing.netlify.app',
    },
    {
      id: 7,
      stack: 'HTML, SCSS, JS',
      title: 'Golden Ring',
      description: 'Website guide to one of the most popular tourist routes "Golden Ring".',
      repository: 'https://github.com/FreightDH/golden-ring',
      deploy: 'https://freightdh.github.io/golden-ring/',
    },
    {
      id: 6,
      stack: 'HTML, SCSS, JS',
      title: 'Minesweeper',
      description: 'Minesweeper game with original design.',
      repository: 'https://github.com/FreightDH/minesweeper',
      deploy: 'https://freightdh-minesweeper.netlify.app',
    },
    {
      id: 5,
      stack: 'HTML, SCSS, JS',
      title: 'Virtual keyboard',
      description: 'A virtual keyboard that supports keyboard or mouse input, two languages.',
      repository: 'https://github.com/FreightDH/virtual-keyboard',
      deploy: 'https://freightdh.github.io/virtual-keyboard/virtual-keyboard/',
    },
    {
      id: 4,
      stack: 'HTML, SCSS, JS',
      title: 'Hangman Game',
      description: 'Guessing game with JavaScript questions and responsive design.',
      repository: 'https://github.com/FreightDH/hangman',
      deploy: 'https://freightdh.github.io/hangman/',
    },
    {
      id: 1,
      stack: 'HTML, SCSS, JS',
      title: 'Momentum',
      description: 'An analogue of the application with the same name from the Chrome extensions store.',
      repository: 'https://github.com/FreightDH/momentum',
      deploy: 'https://freightdh-momentum.netlify.app/',
    },
  ],
  ru: [
    {
      id: 3,
      stack: 'HTML, CSS, JS, PHP',
      title: 'ООО "ЛМК-ИНЖИНИРИНГ"',
      description: 'Надежное решение для труб нефтегазового сортамента',
      repository: '',
      deploy: 'https://lmk-engineering.ru/',
    },
    {
      id: 2,
      stack: 'React, SCSS, JS',
      title: 'Шифт_',
      description: 'Шифт_ - быстрый и уверенный вход в IT тут.',
      repository: 'https://github.com/FreightDH/shift_',
      deploy: 'https://freightdh-shift.netlify.app/',
    },
    {
      id: 12,
      stack: 'HTML, SCSS, JS',
      title: 'Клуб 7 месяцев',
      description:
        'Клуб 7 месяцев - это сервис доставки одного продукта - желаемый оффер в IT компанию - не более, чем за 7 месяцев.',
      repository: 'https://github.com/FreightDH/7-months-club',
      deploy: 'https://freightdh.github.io/7-months-club/',
    },
    {
      id: 11,
      stack: 'React, Redux Toolkit, SCSS, TS',
      title: 'Pizza Delivery',
      description: 'Сайт доставки еды с полной функциональностью.',
      repository: 'https://github.com/FreightDH/pizza-delivery',
      deploy: 'https://freightdh.github.io/pizza-delivery/',
    },
    {
      id: 10,
      stack: 'React, SCSS, TS',
      title: 'Posts App',
      description:
        'Приложение-блог с системой авторизации, пагинацией, а также с возможностью просматривать, удалять и редактировать посты.',
      repository: 'https://github.com/FreightDH/react-projects',
      deploy: 'https://freightdh-posts-app.netlify.app/',
    },
    {
      id: 9,
      stack: 'React, Redux Toolkit, SCSS, TS',
      title: 'TODO App',
      description:
        'Простой менеджер задач с возможностью добавлять, удалять, редактировать и сохранять свои задачи.',
      repository: 'https://github.com/FreightDH/react-projects',
      deploy: 'https://freightdh.github.io/react-projects/todo-app/',
    },
    {
      id: 8,
      stack: 'React, SCSS, TS',
      title: 'Pokemon Cards',
      description: 'Pokemon API с навигацией с помощью React Router и кастомной пагинацией.',
      repository: 'https://github.com/FreightDH/rss-react/tree/main',
      deploy: 'https://freightdh-react-routing.netlify.app',
    },
    {
      id: 7,
      stack: 'HTML, SCSS, JS',
      title: 'Золотое кольцо',
      description: 'Сайт-путеводитель по одному из самых популярных туристических маршрутов "Золотое кольцо"',
      repository: 'https://github.com/FreightDH/golden-ring',
      deploy: 'https://freightdh.github.io/golden-ring/',
    },
    {
      id: 6,
      stack: 'HTML, SCSS, JS',
      title: 'Игра "Сапер"',
      description: 'Игра "Сапер" с оригинальным дизайном.',
      repository: 'https://github.com/FreightDH/minesweeper',
      deploy: 'https://freightdh-minesweeper.netlify.app',
    },
    {
      id: 5,
      stack: 'HTML, SCSS, JS',
      title: 'Виртуальная клавиатура',
      description: 'Виртуальная клавиатура, поддерживающая ввод с клавиатуры и мыши, два языка.',
      repository: 'https://github.com/FreightDH/virtual-keyboard',
      deploy: 'https://freightdh.github.io/virtual-keyboard/virtual-keyboard/',
    },
    {
      id: 4,
      stack: 'HTML, SCSS, JS',
      title: 'Игра "Виселица"',
      description: 'Игра-угадайка с вопросами по JavaScript и отзывчивым дизайном.',
      repository: 'https://github.com/FreightDH/hangman',
      deploy: 'https://freightdh.github.io/hangman/',
    },
    {
      id: 1,
      stack: 'HTML, SCSS, JS',
      title: 'Momentum',
      description: 'Аналог одноименного приложения из магазина расширений Google Chrome.',
      repository: 'https://github.com/FreightDH/momentum',
      deploy: 'https://freightdh-momentum.netlify.app/',
    },
  ],
};

export default projectsInfo;
