const projectsInfo = {
  eng: [
    {
      id: 8,
      stack: 'HTML, CSS, JS, PHP',
      title: 'МХТ им. А.П. Чехова',
      description: 'Participation in the development of a new website for the MXAT',
      repository: '',
      deploy: 'https://mxat.ru/',
    },
    {
      id: 7,
      stack: 'HTML, CSS, JS, PHP',
      title: 'ФРИДОМ',
      description:
        'Updating the main website of the ФРИДОМ real estate agency, developing landing pages for services',
      repository: '',
      deploy: 'https://freedome-realty.ru/',
    },
    {
      id: 6,
      stack: 'HTML, CSS, JS, PHP',
      title: 'Mediahead',
      description: 'Participation in the development of a new website for the Mediahead company',
      repository: '',
      deploy: 'https://mediahead.ru/',
    },
    {
      id: 5,
      stack: 'HTML, CSS, JS, PHP',
      title: 'ООО «ЛМК-ИНЖИНИРИНГ»',
      description: 'Development of the UI of the website with Bitrix integration',
      repository: '',
      deploy: 'https://lmk-engineering.ru/',
    },
    {
      id: 4,
      stack: 'React, Redux Toolkit, SCSS, TS',
      title: 'Pizza Delivery',
      description: 'Food delivery site with full functionality',
      repository: 'https://github.com/FreightDH/pizza-delivery',
      deploy: 'https://freightdh.github.io/pizza-delivery/',
    },
    {
      id: 3,
      stack: 'React, SCSS, TS',
      title: 'Posts App',
      description:
        'Posts App with authorization system, pagination and the ability to view, delete and edit posts',
      repository: 'https://github.com/FreightDH/react-projects',
      deploy: 'https://freightdh-posts-app.netlify.app/',
    },
    {
      id: 2,
      stack: 'HTML, SCSS, JS',
      title: 'Golden Ring',
      description: 'Website guide to one of the most popular tourist routes "Golden Ring"',
      repository: 'https://github.com/FreightDH/golden-ring',
      deploy: 'https://freightdh.github.io/golden-ring/',
    },
    {
      id: 1,
      stack: 'HTML, SCSS, JS',
      title: 'Minesweeper',
      description: 'Minesweeper game with original design',
      repository: 'https://github.com/FreightDH/minesweeper',
      deploy: 'https://freightdh-minesweeper.netlify.app',
    },
  ],
  ru: [
    {
      id: 8,
      stack: 'HTML, CSS, JS, PHP',
      title: 'МХТ им. А.П. Чехова',
      description: 'Участие в разработке нового сайта для МХАТ',
      repository: '',
      deploy: 'https://mxat.ru/',
    },
    {
      id: 7,
      stack: 'HTML, CSS, JS, PHP',
      title: 'ФРИДОМ',
      description: 'Обновление основного сайта агентства недвижимости ФРИДОМ, разработка лендингов услуг',
      repository: '',
      deploy: 'https://freedome-realty.ru/',
    },
    {
      id: 6,
      stack: 'HTML, CSS, JS, PHP',
      title: 'Mediahead',
      description: 'Участие в разработке нового сайта компании Mediahead',
      repository: '',
      deploy: 'https://mediahead.ru/',
    },
    {
      id: 5,
      stack: 'HTML, CSS, JS, PHP',
      title: 'ООО "ЛМК-ИНЖИНИРИНГ"',
      description: 'Разработка клиентской части сайта с интеграцией Bitrix',
      repository: '',
      deploy: 'https://lmk-engineering.ru/',
    },
    {
      id: 4,
      stack: 'React, Redux Toolkit, SCSS, TS',
      title: 'Pizza Delivery',
      description: 'Сайт доставки еды с полной функциональностью',
      repository: 'https://github.com/FreightDH/pizza-delivery',
      deploy: 'https://freightdh.github.io/pizza-delivery/',
    },
    {
      id: 3,
      stack: 'React, SCSS, TS',
      title: 'Posts App',
      description:
        'Приложение-блог с системой авторизации, пагинацией, а также с возможностью просматривать, удалять и редактировать посты',
      repository: 'https://github.com/FreightDH/react-projects',
      deploy: 'https://freightdh-posts-app.netlify.app/',
    },
    {
      id: 2,
      stack: 'HTML, SCSS, JS',
      title: 'Золотое кольцо',
      description: 'Сайт-путеводитель по одному из самых популярных туристических маршрутов "Золотое кольцо"',
      repository: 'https://github.com/FreightDH/golden-ring',
      deploy: 'https://freightdh.github.io/golden-ring/',
    },
    {
      id: 1,
      stack: 'HTML, SCSS, JS',
      title: 'Игра "Сапер"',
      description: 'Игра "Сапер" с оригинальным дизайном',
      repository: 'https://github.com/FreightDH/minesweeper',
      deploy: 'https://freightdh-minesweeper.netlify.app',
    },
  ],
};

export default projectsInfo;
